name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0

      - uses: bahmutov/npm-install@v1

      - name: Run linter
        run: npm run lint-all

      - name : Run test
        run: npm run test-all
